{
 "title": "HPA Recommendation",
 "time": { "from": "now-1h", "to": "now+15m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "show tag values on alameda_cluster_status from pod with key = \"namespace\" where  alameda_scaler_scaling_tool = 'HPA'"
   },
   {
    "name": "scaler",
    "label": "Application",
    "query": "show tag values on alameda_cluster_status from pod with key = \"alameda_scaler_name\" where  namespace = '$ns' and alameda_scaler_scaling_tool = 'HPA'"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "show tag values on alameda_cluster_status from controller with key=\"name\" where \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler'"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "show tag values on alameda_cluster_status from pod with key=\"name\" where \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and \"top_controller_name\" = '$controller'"
   },
   {
    "name": "preloader",
    "label": "Preloader",
    "query": "select preloader from alameda_metric..grafana_config order by time desc limit 1"
   },
   {
    "name": "controller_ns",
    "query": "select namespace, \"policy\" from alameda_cluster_status..pod where alameda_scaler_scaling_tool = 'HPA' and namespace = '$ns' and ('false' = '$preloader' or '' = '$preloader') group by \"namespace\" order by time desc limit 1"
   },
   {
    "name": "deployment_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"name\" = '$controller' and \"kind\" = 'DEPLOYMENT'"
   },
   {
    "name": "deploymentConfig_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"name\" = '$controller' and \"kind\" = 'DEPLOYMENTCONFIG'"
   },
   {
    "name": "statefulset_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"name\" = '$controller' and \"kind\" = 'STATEFULSET'"
   },
   {
    "name": "deployment_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "deploymentConfig_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "statefulset_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "memorys_deployment_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "memorys_deploymentConfig_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "memorys_statefulset_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Managed Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Controllers with HPA ScalingTool per Selected Application",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top_controller_kind as \"kind\", top_controller_name as \"controller\" from (select * from alameda_cluster_status..pod where top_controller_kind = 'STATEFULSET' and alameda_scaler_scaling_tool = 'HPA' and alameda_scaler_name = '$scaler' limit 1), (select * from alameda_cluster_status..pod where top_controller_kind = 'DEPLOYMENT' and alameda_scaler_scaling_tool = 'HPA' and alameda_scaler_name = '$scaler' limit 1), (select * from alameda_cluster_status..pod where top_controller_kind = 'DEPLOYMENTCONFIG' and alameda_scaler_scaling_tool = 'HPA' and alameda_scaler_name = '$scaler' limit 1) group by alameda_scaler_name, namespace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller Resource Usage and Recommendation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Desired Replica",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select desired_replicas as \"desired replicas\" from alameda_recommendation..controller where type = 'PRIMITIVE' and namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Replica",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_statefulset_status_replicas{namespace=\"$ns\",statefulset=\"$controller\"}) or 1-absent(sum(kube_statefulset_status_replicas{namespace=\"$ns\",statefulset=\"$controller\"})))+(sum(kube_deployment_status_replicas{namespace=\"$ns\",deployment=\"$controller\"}) or 1-absent(sum(kube_deployment_status_replicas{namespace=\"$ns\",deployment=\"$controller\"})))+(sum(kube_replicationcontroller_status_replicas{namespace=\"$ns\",replicationcontroller=~\"$controller.*\"}) or 1-absent(sum(kube_replicationcontroller_status_replicas{namespace=\"$ns\",replicationcontroller=~\"$controller.*\"})))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_replicas as \"current replicas\" from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU Limit (milicore)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1000 * sum(sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_cpu_limits from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1\n\nsum(label_replace(\nsum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU Request (milicore)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1000 * sum(sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "1000 * sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$ns\", pod=~\"$controller.*\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Memory Limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_mem_limits from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Memory Request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$pod\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_mem_requests from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Object CPU Usage(milicore) vs Replica Recommendation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\",container_name!=\"POD\"}[30s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "1000 * sum(max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\",container!=\"POD\"}[30s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Recommendation: Desired CPU Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select desired_cpu_limits from \"alameda_recommendation\"..\"controller\" where type = 'PRIMITIVE' and \"name\" = '$controller' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation : CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(value) from alameda_metric..controller_cpu where \"namespace\" = '$ns' and \"name\" = '$controller' and $timeFilter and 'true' = '$preloader' group by time(30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Object Memory vs Replica Recommendation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "round(sum(max_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[30s])))",
     "legendFormat": "Observation : Memory Usage"
    },
    {
     "expr": "round(sum(max_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[30s])))",
     "legendFormat": "Observation : Memory Usage"
    },
    {
     "alias": "Recommendation : Desired Memory Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select round(desired_mem_limits) from \"alameda_recommendation\"..\"controller\" where \"name\" = '$controller' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation : Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select max(value) from alameda_metric..controller_memory where \"namespace\" = '$ns' and \"name\" = '$controller' and $timeFilter and 'true' = '$preloader' group by time(30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}