{
 "title": "Workload Prediction",
 "time": { "from": "now-5M", "to": "now+1M" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "resource",
    "label": "Scope",
    "query": "Cluster, Namespace, Application, Controller"
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "select \"name\" from (select \"name\", value from alameda_cluster_status..namespace where 'Namespace' = '$resource'), (select \"namespace\" as \"name\", \"policy\" from alameda_cluster_status..pod where 'Application' = '$resource' or 'Controller' = '$resource')"
   },
   {
    "name": "scaler",
    "label": "Application",
    "query": "show tag values on alameda_cluster_status from pod with key=\"alameda_scaler_name\"  where \"namespace\" = '$ns'  and 'Namespace' != '$resource'"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": "select \"name\",  \"policy\" from alameda_cluster_status..controller where  \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler'  and 'Controller' = '$resource'"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "select \"name\", scaling_tool from alameda_cluster_status..pod where \"alameda_scaler_namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and \"top_controller_name\" = '$controller' and scaling_tool =~ /VPA/ and 'Controller' = '$resource'"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "show tag values on alameda_cluster_status from container with key=\"name\" where \"pod_name\" = '$pod' and 'Controller' = '$resource'"
   },
   {
    "name": "h_ns",
    "query": "select \"name\", value from (select \"name\", value from alameda_cluster_status..namespace where 'Cluster' = '$resource' group by \"name\"),(select \"name\", value from alameda_cluster_status..namespace where 'Cluster' != '$resource' and \"name\" = '$ns' group by \"name\")"
   },
   {
    "name": "h_scaler",
    "query": "select \"name\", \"value\" from (select \"name\", \"value\" from alameda_cluster_status..application where \"namespace\" =~ /^[[h_ns]]$/  and ('Cluster' = '$resource' or 'Namespace' = '$resource') group by \"name\"), (select \"name\", \"value\" from alameda_cluster_status..application where \"namespace\" ='$ns' and 'Cluster' != '$resource' and 'Namespace' != '$resource' group by \"name\")"
   },
   {
    "name": "h_controller",
    "query": "select \"name\", \"policy\" from  (select \"name\", \"policy\" from alameda_cluster_status..controller where \"namespace\" =~ /^[[h_ns]]$/ and \"alameda_scaler_name\" =~ /^[[h_scaler]]$/ and 'Cluster' = '$resource'), (select \"name\", \"policy\" from alameda_cluster_status..controller where \"namespace\" = '$ns' and \"alameda_scaler_name\" =~ /^[[h_scaler]]$/ and 'Namespace' = '$resource'), (select \"name\", \"policy\" from alameda_cluster_status..controller where \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and 'Application' = '$resource'), (select \"name\", \"policy\" from alameda_cluster_status..controller where \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and \"name\" = '$controller' and 'Controller' = '$resource')"
   },
   {
    "name": "h_pod",
    "label": "h_pod",
    "query": "select \"name\", \"policy\" from (select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\"=~ /^[[h_ns]]$/ and \"alameda_scaler_name\" =~ /^[[h_scaler]]$/ and 'Cluster' = '$resource'), (select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\"= '$ns' and \"alameda_scaler_name\" =~ /^[[h_scaler]]$/ and 'Namespace' = '$resource'), (select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\"= '$ns' and \"alameda_scaler_name\" ='$scaler' and 'Application' = '$resource'), (select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\"= '$ns' and \"alameda_scaler_name\" ='$scaler' and \"name\" = '$pod' and \"alameda_scaler_scaling_tool\" =~ /VPA/ and 'Container' = '$resource')"
   },
   {
    "name": "h_container",
    "label": "h_container",
    "query": "select \"name\", restart_count from (select \"name\", restart_count from alameda_cluster_status..container where \"pod_name\" =~ /^[[h_pod]]$/ and 'Container' != '$resource'),  (select \"name\", restart_count from alameda_cluster_status..container where \"pod_name\" ='$h_pod' and \"name\" = '$container' and 'Container' = '$resource')"
   },
   {
    "name": "count_container",
    "label": "Count",
    "query": "select count(\"name\") from (select \"name\", resource_request_cpu from (select \"name\", resource_request_cpu from alameda_cluster_status..container where \"pod_name\" =~ /^[[h_pod]]$/ and ('Cluster' = '$resource' or 'Namespace' = 'resource' or 'Application' = 'resource')), (select \"name\", resource_request_cpu from alameda_cluster_status..container where \"pod_name\" = '$pod' and 'Container' = '$resource'))"
   },
   {
    "name": "preloader",
    "label": "Preloader",
    "query": "select preloader from alameda_metric..grafana_config order by time desc limit 1"
   },
   {
    "name": "node",
    "query": "show tag values on alameda_cluster_status from node with key = \"name\" where 'Cluster' = '$resource' and ('false' = '$preloader' or '' = '$preloader')"
   },
   {
    "name": "namespace_ns",
    "query": "select \"name\", value from alameda_cluster_status..namespace where 'Namespace' = '$resource' and ('false' = '$preloader' or '' = '$preloader') and \"name\" = '$ns'"
   },
   {
    "name": "app_ns",
    "query": "select namespace, \"policy\" from alameda_cluster_status..pod where 'Application' = '$resource' and ('false' = '$preloader' or '' = '$preloader') and namespace = '$ns' group by \"namespace\" order by time desc limit 1"
   },
   {
    "name": "container_ns",
    "query": "select alameda_scaler_namespace, \"policy\" from alameda_cluster_status..pod where 'Container' = '$resource' and ('false' = '$preloader' or '' = '$preloader') group by \"namespace\" order by time desc limit 1"
   },
   {
    "name": "controller_ns",
    "query": "select \"namespace\", \"policy\" from alameda_cluster_status..controller where 'Controller' = '$resource' and ('false' = '$preloader' or '' = '$preloader') and namespace = '$ns' group by \"namespace\" order by time desc limit 1"
   },
   {
    "name": "deployment_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"kind\" = 'DEPLOYMENT'"
   },
   {
    "name": "deploymentConfig_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"kind\" = 'DEPLOYMENTCONFIG'"
   },
   {
    "name": "statefulset_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"kind\" = 'STATEFULSET'"
   },
   {
    "name": "deployment_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "deploymentConfig_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "statefulset_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "memorys_deployment_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "memorys_deploymentConfig_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "memorys_statefulset_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "selected_deployment_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"name\" = '$controller' and \"kind\" = 'DEPLOYMENT'"
   },
   {
    "name": "selected_deploymentConfig_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"name\" = '$controller' and \"kind\" = 'DEPLOYMENTCONFIG'"
   },
   {
    "name": "selected_statefulset_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"name\" = '$controller' and \"kind\" = 'STATEFULSET'"
   },
   {
    "name": "selected_cpu_deployment_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "selected_cpu_deploymentConfig_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "selected_cpu_statefulset_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "selected_memorys_deployment_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "selected_memorys_deploymentConfig_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "selected_memorys_statefulset_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   }
  ]
 },
 "panels": [
  { "title": "Managed Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select restart_count,  \"name\" as \"container\",  \"namespace\", \"pod_name\" as pod, \"node_name\" as node from alameda_cluster_status..container ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"policy\", \"alameda_scaler_name\", \"name\" as pod from alameda_cluster_status..pod",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Managed Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select create_time *1000 , \"name\", node_cpu_cores, node_memory_bytes, in_cluster from alameda_cluster_status..node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 7 },
   "content": "<script>\n$( document ).ready(function() {\n  for (var i = 1; i <= 5; i++) {\n    var el = document.getElementsByClassName(\"variable-value-link\")[i];\n    if(el.childNodes && el.childNodes[0].nodeValue.indexOf('None') !== -1) {\n\t    el.childNodes[0].nodeValue = el.childNodes[0].nodeValue.replace('None', 'N/A')\n    }\n  }\n  $(document).on(\"click\",\".gf-form-inline\",function() {\n    if ($('.navbar-page-btn')[0].innerText.trim() !== 'Workload Prediction') return\n    var option = $('.variable-option')[0];\n    if(option.childNodes && option.childNodes[3].childNodes[0].nodeValue.indexOf('None') !== -1) {\n       option.childNodes[3].childNodes[0].nodeValue = option.childNodes[3].childNodes[0].nodeValue.replace('None', 'N/A')\n    }\n  });\n  \n});\n\n$(\".variable-value-link\").on('DOMSubtreeModified', function () {\n  if ($('.navbar-page-btn')[0].innerText.trim() !== 'Workload Prediction') return\n if(this.childNodes && this.childNodes[0].nodeValue.indexOf('None') !== -1) {\n\t  this.childNodes[0].nodeValue = this.childNodes[0].nodeValue.replace('None', 'N/A')\n  }\n});\n</script>\n<style>\n  #panel-56 {\n    display:none;\n  }\n</style>"
  },
  {
   "title": "Resource Usage (5 days + 1 day)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "CPU: Observation, and Prediction (in CPU milicore)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(1000 * avg_over_time(node:node_cpu_utilisation:avg1m{node=~\"$node\"}[3600s]) * avg_over_time(node:node_num_cpu:sum{node=~\"$node\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum (1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace_ns\", namespace!=\"\", pod_name!=\"\",container_name!=\"POD\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum (1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace_ns\", namespace!=\"\", pod!=\"\",container!=\"POD\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum (1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum (1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$app_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum (1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum (1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Prediction: CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5d and time <= now() + 1d and 'Cluster' = '$resource' group by time(3600s)),\n( select sum(value) from \"alameda_prediction\"..\"namespace\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5d and time <= now() + 1d and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(3600s)),\n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5d and time <= now() + 1d and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(3600s)),\n( select sum(value) from \"alameda_prediction\"..\"controller\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5d and time <= now() + 1d and \"name\" = '$controller'  and namespace = '$ns' and 'Controller' = '$resource' group by time(3600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation : CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(mean) from (select mean(value) from alameda_metric..cluster_cpu where time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Cluster' = '$resource' group by time(3600s)), (select mean(value) from alameda_metric..namespace_cpu where \"name\" = '$ns' and time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Namespace' = '$resource' group by time(3600s)), (select mean(value) from alameda_metric..application_cpu where \"name\" = '$scaler' and \"namespace\" =~ /^[[ns]]$/ and time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Application' = '$resource' group by time(3600s)), (select mean(value) from alameda_metric..controller_cpu where \"name\" = '$controller' and \"namespace\" = '$ns' and time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Controller' = '$resource' group by time(3600s)) where time >= now() -5d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"cluster\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '3600' and time >= now() and time <= now() + 1d and 'Cluster' = '$resource' group by time(3600s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"namespace\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '3600' and time >= now() and time <= now() + 1d and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(3600s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"application\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '3600' and time >= now() and time <= now() + 1d and \"name\" = '$scaler' and namespace = '$ns' and 'Application' = '$resource' group by time(3600s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"controller\" where granularity = '3600' and \"planning_type\" = 'PT_RECOMMENDATION' and time >= now() and time <= now() + 1d and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(3600s))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(node:node_memory_bytes_total:sum{node=~\"$node\"}[3600s]) * avg_over_time(node:node_memory_utilisation_2:{node=~\"$node\"}[3600s]))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace_ns\", namespace!=\"\", pod_name!=\"\", container_name!=\"\",container_name!=\"POD\"}[3600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace_ns\", namespace!=\"\", pod!=\"\", container!=\"\",container!=\"POD\"}[3600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[3600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$app_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[3600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[3600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[3600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "alias": "Prediction: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5d and time <= now() + 1d and 'Cluster' = '$resource' group by time(3600s)),\n( select sum(value) from \"alameda_prediction\"..\"namespace\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5d and time <= now() + 1d and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(3600s)),\n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5d and time <= now() + 1d and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(3600s)),\n( select sum(value) from \"alameda_prediction\"..\"controller\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5d and time <= now() + 1d and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(3600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(mean) from (select mean(value) from alameda_metric..cluster_memory where time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Cluster' = '$resource' group by time(3600s)), (select mean(value) from alameda_metric..namespace_memory where \"name\" = '$ns' and time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Namespace' = '$resource' group by time(3600s)), (select mean(value) from alameda_metric..application_memory where \"name\" = '$scaler' and \"namespace\" =~ /^[[ns]]$/ and time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Application' = '$resource' group by time(3600s)), (select mean(value) from alameda_metric..controller_memory where \"namespace\" = '$ns' and \"name\" = '$controller' and time >= now() -5d and time <= now() + 1d and 'true' = '$preloader' and 'Controller' = '$resource' group by time(3600s)) where time >= now() -5d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from\n( select sum(resource_request_memory) from \"alameda_planning\"..\"cluster\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '3600' and time >= now() and time <= now() + 1d and 'Cluster' = '$resource' group by time(3600s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"namespace\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '3600' and time >= now() and time <= now() + 1d and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(3600s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"application\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '3600' and time >= now() and time <= now() + 1d and \"name\" = '$scaler' and namespace = '$ns' and 'Application' = '$resource' group by time(3600s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"controller\" where granularity = '3600' and \"planning_type\" = 'PT_RECOMMENDATION' and time >= now() and time <= now() + 1d and \"name\" = '$controller' and  namespace = '$ns' and namespace = '$ns' and 'Controller' = '$resource' group by time(3600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Usage (5 weeks + 1 week)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "CPU: Observation, and Prediction (in CPU milicore)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(1000 * avg_over_time(node:node_cpu_utilisation:avg1m{node=~\"$node\"}[21600s]) * avg_over_time(node:node_num_cpu:sum{node=~\"$node\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace_ns\", namespace!=\"\", pod_name!=\"\",container_name!=\"POD\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace_ns\", namespace!=\"\", pod!=\"\",container!=\"POD\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$app_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\"}[21600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Prediction: CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5w and time <= now() + 1w and 'Cluster' = '$resource' group by time(21600s)),\n( select sum(value) from \"alameda_prediction\"..\"namespace\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5w and time <= now() + 1w and 'Namespace' = '$resource' and \"name\" = '$ns' group by time(21600s)),\n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5w and time <= now() + 1w and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(21600s)),\n( select sum(value) from \"alameda_prediction\"..\"controller\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5w and time <= now() + 1w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(21600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation : CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(mean) from (select mean(value) from alameda_metric..cluster_cpu where time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Cluster' = '$resource' group by time(21600s)), (select mean(value) from alameda_metric..namespace_cpu where \"name\" = '$ns' and time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Namespace' = '$resource' group by time(21600s)), (select mean(value) from alameda_metric..application_cpu where \"name\" = '$scaler' and \"namespace\" =~ /^[[ns]]$/ and time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Application' = '$resource' group by time(21600s)), (select mean(value) from alameda_metric..controller_cpu where \"namespace\" = '$ns' and \"name\" = '$controller' and time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Controller' = '$resource' group by time(21600s)) where time >= now() -5w and time <= now() + 1w group by time(21600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"cluster\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '21600' and time >= now()  and time <= now() + 1w and 'Cluster' = '$resource' group by time(21600s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"namespace\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '21600' and time >= now()  and time <= now() + 1w and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(21600s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"application\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '21600' and time >= now()  and time <= now() + 1w and \"name\" = '$scaler' and namespace = '$ns' and 'Application' = '$resource' group by time(21600s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"controller\" where granularity = '21600' and \"planning_type\" = 'PT_RECOMMENDATION' and time >= now()  and time <= now() + 1w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(21600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(node:node_memory_bytes_total:sum{node=~\"$node\"}[21600s]) * avg_over_time(node:node_memory_utilisation_2:{node=~\"$node\"}[21600s]))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace_ns\", namespace!=\"\", pod_name!=\"\", container_name!=\"\",container_name!=\"POD\"}[21600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace_ns\", namespace!=\"\", pod!=\"\", container!=\"\",container!=\"POD\"}[21600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[21600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$app_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[21600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[21600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[21600s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "alias": "Prediction: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5w and time <= now() + 1w and 'Cluster' = '$resource' group by time(21600s)),\n( select sum(value) from \"alameda_prediction\"..\"namespace\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5w and time <= now() + 1w and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(21600s)),\n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5w and time <= now() + 1w and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(21600s)),\n( select sum(value) from \"alameda_prediction\"..\"controller\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5w and time <= now() + 1w and \"name\" = '$controller'  and namespace = '$ns' and 'Controller' = '$resource' group by time(21600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(mean) from (select mean(value) from alameda_metric..cluster_memory where time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Cluster' = '$resource' group by time(21600s)), (select mean(value) from alameda_metric..namespace_memory where \"name\" = '$ns' and time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Namespace' = '$resource' group by time(21600s)), (select mean(value) from alameda_metric..application_memory where \"name\" = '$scaler' and \"namespace\" =~ /^[[ns]]$/ and time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Application' = '$resource' group by time(21600s)), (select mean(value) from alameda_metric..controller_memory where \"namespace\" = '$ns' and \"name\" = '$controller' and time >= now() -5w and time <= now() + 1w and 'true' = '$preloader' and 'Controller' = '$resource' group by time(21600s)) where time >= now() -5w and time <= now() + 1w group by time(21600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from\n( select sum(resource_request_memory) from \"alameda_planning\"..\"cluster\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '21600' and time >= now()  and time <= now() + 1w and 'Cluster' = '$resource' group by time(21600s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"namespace\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '21600' and time >= now()  and time <= now() + 1w and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(21600s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"application\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '21600' and time >= now()  and time <= now() + 1w and \"name\" = '$scaler' and namespace = '$ns' and 'Application' = '$resource' group by time(21600s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"controller\" where granularity = '21600' and \"planning_type\" = 'PT_RECOMMENDATION' and time >= now()  and time <= now() + 1w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(21600s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Usage (5 months + 1 month)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 }
  },
  {
   "title": "CPU: Observation, and Prediction (in CPU milicore)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(1000 * avg_over_time(node:node_cpu_utilisation:avg1m{node=~\"$node\"}[86400s]) * avg_over_time(node:node_num_cpu:sum{node=~\"$node\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace_ns\", namespace!=\"\", pod_name!=\"\",container_name!=\"POD\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$namespace_ns\", namespace!=\"\", pod!=\"\",container!=\"POD\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$app_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum( 1000 * avg_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\"}[86400s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Prediction: CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 20w and time <= now() + 4w and 'Cluster' = '$resource' group by time(86400s)),\n( select sum(value) from \"alameda_prediction\"..\"namespace\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 20w  and time <= now() + 4w and 'Namespace' = '$resource' and \"name\" = '$ns' group by time(86400s)),\n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 20w and time <= now() + 4w and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(86400s)),\n( select sum(value) from \"alameda_prediction\"..\"controller\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 20w and time <= now() + 4w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(86400s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation : CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(mean) from (select mean(value) from alameda_metric..cluster_cpu where time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Cluster' = '$resource' group by time(86400s)), (select mean(value) from alameda_metric..namespace_cpu where \"name\" = '$ns' and time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Namespace' = '$resource' group by time(86400s)), (select mean(value) from alameda_metric..application_cpu where \"name\" = '$scaler' and \"namespace\" =~ /^[[ns]]$/ and time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Application' = '$resource' group by time(86400s)), (select mean(value) from alameda_metric..controller_cpu where \"name\" = '$controller' and \"namespace\" = '$ns' and time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Controller' = '$resource' group by time(86400s)) where time >= now() -20w and time <= now() + 4w group by time(86400s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"cluster\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '86400' and time >= now() and time <= now() + 4w and 'Cluster' = '$resource' group by time(86400s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"namespace\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '86400' and time >= now() and time <= now() + 4w and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(86400s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"application\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '86400' and time >= now() and time <= now() + 4w and \"name\" = '$scaler' and namespace = '$ns' and 'Application' = '$resource' group by time(86400s)),\n( select sum(resource_request_cpu) from \"alameda_planning\"..\"controller\" where granularity = '86400' and \"planning_type\" = 'PT_RECOMMENDATION' and time >= now() and time <= now() + 4w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(86400s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (avg_over_time(node:node_memory_bytes_total:sum{node=~\"$node\"}[86400s]) * avg_over_time(node:node_memory_utilisation_2:{node=~\"$node\"}[86400s]))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace_ns\", namespace!=\"\", pod_name!=\"\", container_name!=\"\",container_name!=\"POD\"}[86400s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace_ns\", namespace!=\"\", pod!=\"\", container!=\"\",container!=\"POD\"}[86400s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[86400s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$app_ns\", namespace!=\"\", pod=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[86400s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod_name=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[86400s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(avg_over_time(container_memory_usage_bytes{namespace=~\"$controller_ns\", namespace!=\"\", pod=~\"($selected_deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($selected_deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($selected_statefulset_controller)-[0-9]+$\", pod!=\"\", container!=\"POD\", container!=\"\"}[86400s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "alias": "Prediction: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'memory_usage_bytes' and time >= now() - 20w and time <= now() + 4w and 'Cluster' = '$resource' group by time(86400s)),\n( select sum(value) from \"alameda_prediction\"..\"namespace\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'memory_usage_bytes' and time >= now() - 20w and time <= now() + 4w and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(86400s)),\n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'memory_usage_bytes' and time >= now() - 20w and time <= now() + 4w and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(86400s)),\n( select sum(value) from \"alameda_prediction\"..\"controller\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'memory_usage_bytes' and time >= now() - 20w and time <= now() + 4w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(86400s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Observation: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(mean) from (select mean(value) from alameda_metric..cluster_memory where time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Cluster' = '$resource' group by time(86400s)), (select mean(value) from alameda_metric..namespace_memory where \"name\" = '$ns' and time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Namespace' = '$resource' group by time(86400s)), (select mean(value) from alameda_metric..application_memory where \"name\" = '$scaler' and \"namespace\" =~ /^[[ns]]$/ and time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Application' = '$resource' group by time(86400s)), (select mean(value) from alameda_metric..controller_memory where \"namespace\" = '$ns' and \"name\" = '$controller' and time >= now() -20w and time <= now() + 4w and 'true' = '$preloader' and 'Controller' = '$resource' group by time(86400s)) where time >= now() -20w and time <= now() + 4w group by time(86400s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from\n( select sum(resource_request_memory) from \"alameda_planning\"..\"cluster\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '86400' and time >= now() and time <= now() + 4w and 'Cluster' = '$resource' group by time(86400s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"namespace\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '86400' and time >= now() and time <= now() + 4w and \"name\" = '$ns' and 'Namespace' = '$resource' group by time(86400s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"application\" where \"planning_type\" = 'PT_RECOMMENDATION' and granularity = '86400' and time >= now() and time <= now() + 4w and \"name\" = '$scaler' and namespace = '$ns' and 'Application' = '$resource' group by time(86400s)),\n( select sum(resource_request_memory) from \"alameda_planning\"..\"controller\" where granularity = '86400' and \"planning_type\" = 'PT_RECOMMENDATION' and time >= now() and time <= now() + 4w and \"name\" = '$controller' and namespace = '$ns' and 'Controller' = '$resource' group by time(86400s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}